version: '3.5'

services:
  app:
    container_name: python-stack-test
    build:
      context: ./
      dockerfile: app.dockerfile
    ports:
      - 3005:8000
    volumes:
      - ./:/code
    working_dir: /code
